from datetime import UTC, datetime

from kotekomi_domain import (
    Actor,
    ArgumentEdge,
    ArgumentEdgeRelation,
    Assertion,
    AssertionStatus,
    AssertionType,
    AttributionBasis,
    Briefing,
    Document,
    Entity,
    EntityKind,
    EpistemicScope,
    Event,
    EvidenceSpan,
    Organization,
    Outcome,
    Place,
    ProposedChange,
    ProvenanceActivity,
    Relationship,
    SelectorType,
    Source,
    SourceAuthority,
    SourceType,
)

NOW = datetime(2026, 7, 8, tzinfo=UTC)
HASH = "a" * 64


def sample_domain_records() -> tuple[
    Entity,
    Actor,
    Organization,
    Place,
    Event,
    Source,
    Document,
    EvidenceSpan,
    Assertion,
    Relationship,
    Outcome,
    ArgumentEdge,
    ProvenanceActivity,
    ProposedChange,
    Briefing,
]:
    return (
        Entity(id="ent_actor_a", entity_kind=EntityKind.ACTOR, canonical_name="Person A"),
        Actor(id="act_person_a", name="Person A", role_names=("advisor",)),
        Organization(id="org_lab_a", name="Lab A"),
        Place(id="plc_event_hall", name="Event Hall"),
        Event(
            id="evt_model_forum",
            name="Model Forum",
            start_at=NOW,
            place_id="plc_event_hall",
            participant_actor_ids=("act_person_a",),
            participant_organization_ids=("org_lab_a",),
        ),
        Source(
            id="src_article_a",
            source_type=SourceType.ARTICLE,
            title="Release review article",
            uri="https://example.test/release-review",
            published_at=NOW,
        ),
        Document(
            id="doc_article_a",
            source_id="src_article_a",
            raw_path="archive/raw/src_article_a.html",
            extracted_text_path="archive/extracted/doc_article_a.txt",
            content_sha256=HASH,
        ),
        EvidenceSpan(
            id="evs_article_a_release",
            source_id="src_article_a",
            document_id="doc_article_a",
            assertion_id="ast_release_review",
            selector_type=SelectorType.EXACT_TEXT,
            exact_text="Person A negotiated the release.",
        ),
        Assertion(
            id="ast_release_review",
            assertion_type=AssertionType.SOURCE_CLAIM,
            epistemic_scope=EpistemicScope.SOURCE_REPORT,
            subject_entity_id="act_person_a",
            predicate="negotiated_release",
            object_entity_id="org_lab_a",
            status=AssertionStatus.REPORTED,
            source_authority=SourceAuthority.SECONDARY,
            attribution_basis=AttributionBasis.REPORTED_BY_SOURCE,
            source_report_confidence=0.9,
            extraction_confidence=0.8,
            world_truth_confidence=0.6,
            source_ids=("src_article_a",),
            evidence_span_ids=("evs_article_a_release",),
            provenance_activity_ids=("prv_human_review",),
        ),
        Relationship(
            id="rel_person_a_lab_a",
            subject_id="act_person_a",
            predicate="negotiated_release",
            object_id="org_lab_a",
            assertion_ids=("ast_release_review",),
        ),
        Outcome(
            id="out_release_review",
            description="The release review became public.",
            actor_ids=("act_person_a",),
            organization_ids=("org_lab_a",),
            event_ids=("evt_model_forum",),
            assertion_ids=("ast_release_review",),
        ),
        ArgumentEdge(
            id="arg_release_support",
            from_assertion_id="ast_release_review",
            to_assertion_id="ast_release_review",
            relation=ArgumentEdgeRelation.SUPPORTS,
            rationale="The source claim supports itself as reported evidence.",
            evidence_span_ids=("evs_article_a_release",),
            confidence=0.8,
        ),
        ProvenanceActivity(
            id="prv_human_review",
            activity_type="human_review",
            agent="analyst",
            input_ids=("pcg_release_review",),
            output_ids=("ast_release_review",),
            occurred_at=NOW,
        ),
        ProposedChange(
            id="pcg_release_review",
            proposed_json={"kind": "Assertion", "id": "ast_release_review"},
            source_id="src_article_a",
            document_id="doc_article_a",
            model_name="local-extraction-model",
            prompt_id="propose_assertions",
            provenance_activity_id="prv_human_review",
        ),
        Briefing(
            id="brf_daily",
            title="Daily Briefing",
            assertion_ids=("ast_release_review",),
            relationship_ids=("rel_person_a_lab_a",),
            argument_edge_ids=("arg_release_support",),
            source_ids=("src_article_a",),
            evidence_span_ids=("evs_article_a_release",),
            provenance_activity_id="prv_human_review",
            markdown_path="briefings/daily/brf_daily.md",
            generated_at=NOW,
        ),
    )
