"""Application Layer Ports."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Protocol

from kotekomi_domain import (
    Actor,
    ArgumentEdge,
    Assertion,
    Briefing,
    Document,
    Entity,
    Event,
    EvidenceSpan,
    Organization,
    Outcome,
    Place,
    ProposedChange,
    ProvenanceActivity,
    Relationship,
    Source,
)
from kotekomi_domain.models import JsonValue


@dataclass(frozen=True)
class LedgerInitResult:
    ledger_path: Path
    applied_migrations: tuple[str, ...]


class LedgerInitializer(Protocol):
    def initialize(self) -> LedgerInitResult: ...


@dataclass(frozen=True)
class ArchiveObject:
    relative_path: str
    size_bytes: int


class ArchiveStore(Protocol):
    def initialize(self) -> None: ...
    def write_raw_source(self, source_id: str, content: bytes) -> ArchiveObject: ...
    def read_raw_source(self, source_id: str) -> bytes: ...
    def write_document_text(self, document_id: str, text: str) -> ArchiveObject: ...
    def read_document_text(self, document_id: str) -> str: ...


@dataclass(frozen=True)
class ModelProposal:
    record_type: str
    stable_label: str
    record: dict[str, JsonValue]
    evidence: dict[str, JsonValue]


class ModelRuntime(Protocol):
    @property
    def model_name(self) -> str: ...

    @property
    def prompt_id(self) -> str: ...

    def propose_assertions(
        self,
        *,
        document_id: str,
        source_id: str,
        document_text: str,
    ) -> tuple[ModelProposal, ...]: ...


class LedgerRepository(Protocol):
    def save_entity(self, record: Entity) -> None: ...
    def get_entity(self, record_id: str) -> Entity | None: ...
    def list_entities(self) -> tuple[Entity, ...]: ...
    def delete_entity(self, record_id: str) -> None: ...

    def save_actor(self, record: Actor) -> None: ...
    def get_actor(self, record_id: str) -> Actor | None: ...
    def list_actors(self) -> tuple[Actor, ...]: ...
    def delete_actor(self, record_id: str) -> None: ...

    def save_organization(self, record: Organization) -> None: ...
    def get_organization(self, record_id: str) -> Organization | None: ...
    def list_organizations(self) -> tuple[Organization, ...]: ...
    def delete_organization(self, record_id: str) -> None: ...

    def save_place(self, record: Place) -> None: ...
    def get_place(self, record_id: str) -> Place | None: ...
    def list_places(self) -> tuple[Place, ...]: ...
    def delete_place(self, record_id: str) -> None: ...

    def save_event(self, record: Event) -> None: ...
    def get_event(self, record_id: str) -> Event | None: ...
    def list_events(self) -> tuple[Event, ...]: ...
    def delete_event(self, record_id: str) -> None: ...

    def save_source(self, record: Source) -> None: ...
    def get_source(self, record_id: str) -> Source | None: ...
    def list_sources(self) -> tuple[Source, ...]: ...
    def delete_source(self, record_id: str) -> None: ...

    def save_document(self, record: Document) -> None: ...
    def get_document(self, record_id: str) -> Document | None: ...
    def list_documents(self) -> tuple[Document, ...]: ...
    def delete_document(self, record_id: str) -> None: ...

    def save_evidence_span(self, record: EvidenceSpan) -> None: ...
    def get_evidence_span(self, record_id: str) -> EvidenceSpan | None: ...
    def list_evidence_spans(self) -> tuple[EvidenceSpan, ...]: ...
    def delete_evidence_span(self, record_id: str) -> None: ...

    def save_assertion(self, record: Assertion) -> None: ...
    def get_assertion(self, record_id: str) -> Assertion | None: ...
    def list_assertions(self) -> tuple[Assertion, ...]: ...
    def delete_assertion(self, record_id: str) -> None: ...

    def save_relationship(self, record: Relationship) -> None: ...
    def get_relationship(self, record_id: str) -> Relationship | None: ...
    def list_relationships(self) -> tuple[Relationship, ...]: ...
    def delete_relationship(self, record_id: str) -> None: ...

    def save_outcome(self, record: Outcome) -> None: ...
    def get_outcome(self, record_id: str) -> Outcome | None: ...
    def list_outcomes(self) -> tuple[Outcome, ...]: ...
    def delete_outcome(self, record_id: str) -> None: ...

    def save_argument_edge(self, record: ArgumentEdge) -> None: ...
    def get_argument_edge(self, record_id: str) -> ArgumentEdge | None: ...
    def list_argument_edges(self) -> tuple[ArgumentEdge, ...]: ...
    def delete_argument_edge(self, record_id: str) -> None: ...

    def save_provenance_activity(self, record: ProvenanceActivity) -> None: ...
    def get_provenance_activity(self, record_id: str) -> ProvenanceActivity | None: ...
    def list_provenance_activities(self) -> tuple[ProvenanceActivity, ...]: ...
    def delete_provenance_activity(self, record_id: str) -> None: ...

    def save_proposed_change(self, record: ProposedChange) -> None: ...
    def get_proposed_change(self, record_id: str) -> ProposedChange | None: ...
    def list_proposed_changes(self) -> tuple[ProposedChange, ...]: ...
    def delete_proposed_change(self, record_id: str) -> None: ...

    def save_briefing(self, record: Briefing) -> None: ...
    def get_briefing(self, record_id: str) -> Briefing | None: ...
    def list_briefings(self) -> tuple[Briefing, ...]: ...
    def delete_briefing(self, record_id: str) -> None: ...
